function mulberry32(a) {
  return function() {
    var t = a += 0x6D2B79F5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  }
}

function rngFactory(seed) {
  if (seed == null || seed === '') return Math.random;
  var n = Number(seed) | 0;
  return mulberry32(n);
}

function generateTicket(rng){
  const pool = Array.from({length:45}, (_,i)=>i+1);
  const out = [];
  for(let i=0;i<6;i++){
    const idx = Math.floor(rng() * pool.length);
    out.push(pool.splice(idx,1)[0]);
  }
  out.sort((a,b)=>a-b);
  return out;
}

function formatTicket(nums){
  return nums.map(n=>String(n).padStart(2,'0')).join(' ');
}

function createSupabaseClient(url, key){
  if(!url || !key) return null;
  if(typeof supabase === 'undefined' || typeof supabase.createClient !== 'function'){
    console.warn('Supabase client 라이브러리를 불러올 수 없습니다. save 기능만 동작하지 않습니다.');
    return null;
  }
  return supabase.createClient(url, key);
}

function getRuntimeEnv() {
  if (typeof window === 'undefined') return {};
  return window.__ENV__ || {};
}

document.addEventListener('DOMContentLoaded', ()=>{
  const runtimeEnv = getRuntimeEnv();
  const supabaseUrl = runtimeEnv.SUPABASE_URL || '';
  const supabaseAnonKey = runtimeEnv.SUPABASE_ANON_KEY || '';
  const supabaseTableName = runtimeEnv.SUPABASE_TABLE_NAME || 'lotto_draws';

  const countEl = document.getElementById('count');
  const seedEl = document.getElementById('seed');
  const genBtn = document.getElementById('generate');
  const copyBtn = document.getElementById('copy');
  const saveBtn = document.getElementById('save');
  const saveStatus = document.getElementById('save-status');
  const results = document.getElementById('results');
  let latestTickets = [];
  const supabaseClient = createSupabaseClient(supabaseUrl, supabaseAnonKey);

  function render(tickets){
    latestTickets = tickets;
    results.innerHTML = '';
    tickets.forEach((t,i)=>{
      const wrap = document.createElement('div');
      wrap.className = 'ticket';
      const label = document.createElement('div');
      label.className = 'ticket-label';
      label.textContent = `티켓 ${i+1}`;
      wrap.appendChild(label);
      t.forEach(n=>{
        const chip = document.createElement('div');
        chip.className = 'chip';
        chip.textContent = String(n).padStart(2,'0');
        wrap.appendChild(chip);
      });
      results.appendChild(wrap);
    });
  }

  genBtn.addEventListener('click', ()=>{
    const c = Math.max(1, Math.min(20, Number(countEl.value) || 1));
    const rng = rngFactory(seedEl.value);
    const tickets = [];
    for(let i=0;i<c;i++) tickets.push(generateTicket(rng));
    render(tickets);
  });

  copyBtn.addEventListener('click', ()=>{
    const text = Array.from(results.querySelectorAll('.ticket')).map(t=>{
      const chips = Array.from(t.querySelectorAll('.chip')).map(c=>c.textContent).join(' ');
      return chips;
    }).join('\n');
    if(!text) return;
    navigator.clipboard?.writeText(text).then(()=>{
      copyBtn.textContent = '복사됨';
      setTimeout(()=>copyBtn.textContent='복사',1000);
    }).catch(()=>{});
  });

  saveBtn.addEventListener('click', async ()=>{
    if(latestTickets.length === 0){
      saveStatus.textContent = '저장할 번호를 먼저 생성하세요.';
      return;
    }
    if(!supabaseClient){
      saveStatus.textContent = 'Supabase 연결이 설정되지 않았습니다.';
      return;
    }

    saveBtn.disabled = true;
    saveStatus.textContent = '저장 중...';

    const payload = latestTickets.map((numbers, index)=>({
      ticket_index: index + 1,
      seed: seedEl.value || null,
      numbers,
      formatted: formatTicket(numbers),
    }));

    console.debug('Supabase save payload:', payload);

    try {
      // include .select() to return created rows when available
      const res = await supabaseClient.from(supabaseTableName).insert(payload).select();
      console.debug('Supabase insert response:', res);
      if(res.error){
        saveStatus.textContent = `저장 실패: ${res.error.message}`;
        console.error('Supabase insert error object:', res.error);
      } else if(res.data){
        saveStatus.textContent = `저장 완료: ${res.data.length}개 티켓을 저장했습니다.`;
      } else {
        saveStatus.textContent = '저장 완료 (응답 없음).';
      }
    } catch (e) {
      console.error('Supabase insert exception:', e);
      saveStatus.textContent = `저장 실패: ${e.message || e}`;
    } finally {
      saveBtn.disabled = false;
    }
  });

  // load historical draws (recent 8 weeks) from local JSON generated by fetch_draws.py
  function renderHistory(data){
    const list = document.getElementById('history-list');
    if(!list) return;
    list.innerHTML = '';
    data.draws.forEach((d,i)=>{
      const wrap = document.createElement('div');
      wrap.className = 'ticket';
      const label = document.createElement('div');
      label.className = 'ticket-label';
      label.textContent = `회차 ${d.draw_no || i+1}`;
      wrap.appendChild(label);
      d.numbers.forEach(n=>{
        const chip = document.createElement('div');
        chip.className = 'chip';
        chip.textContent = String(n).padStart(2,'0');
        wrap.appendChild(chip);
      });
      if(d.bonus){
        const b = document.createElement('div');
        b.className = 'chip';
        b.textContent = 'B+' + String(d.bonus).padStart(2,'0');
        wrap.appendChild(b);
      }
      list.appendChild(wrap);
    });
  }

  fetch('draws.json').then(r=>{
    if(!r.ok) throw new Error('no draws.json');
    return r.json();
  }).then(data=>{
    // ensure structure: {draws:[{numbers:[..], bonus:?}]}
    if(data && Array.isArray(data.draws)){
      renderHistory(data);
    }
  }).catch(()=>{
    // silently ignore if file missing; user can run fetch_draws.py to generate
  });
});
